

DB2000_Control.Machine.OP_StartButton:=FALSE;
DB2000_Control.Machine.OP_StopButton:=FALSE;
DB2000_Control.Machine.OP_ResetButton:=FALSE ;
DB2000_Control.Machine.OP_AutoManual:=FALSE;
DB2000_Control.Machine.AirPresure:=TRUE;

DB2050_DriveControl.DoubleStart[1].Button1:=FALSE; 

DB2000_Control.Machine.Emg_Stop[0]:=TRUE;
DB2000_Control.Machine.Emg_Stop[1]:=TRUE;
DB2000_Control.Machine.Emg_Stop[2]:=TRUE;
DB2000_Control.Machine.Emg_Stop[3]:=TRUE;
DB2000_Control.Machine.Emg_Stop[4]:=TRUE;

DB2000_Control.Machine.SafetyDoor[0]:=TRUE;
DB2000_Control.Machine.SafetyDoor[1]:=TRUE;
DB2000_Control.Machine.SafetyDoor[2]:=TRUE;
DB2000_Control.Machine.SafetyDoor[3]:=TRUE;
DB2000_Control.Machine.SafetyDoor[4]:=TRUE;
DB2000_Control.Machine.SafetyDoor[5]:=TRUE;
DB2000_Control.Machine.SafetyDoor[6]:=TRUE;
DB2000_Control.Machine.SafetyDoor[7]:=TRUE;



