

DB8000_Control.Machine.OP_StartButton:=FALSE;
DB8000_Control.Machine.OP_StopButton:=FALSE;
DB8000_Control.Machine.OP_ResetButton:=FALSE ;
DB8000_Control.Machine.OP_AutoManual:=FALSE;
DB8000_Control.Machine.AirPresure:=TRUE;

DB8050_DriveControl.DoubleStart[1].Button1:=TRUE;
DB8050_DriveControl.DoubleStart[1].Button2:=TRUE;
DB8050_DriveControl.DoubleStart[2].Button1:=TRUE;
DB8050_DriveControl.DoubleStart[2].Button2:=TRUE;
DB8050_DriveControl.DoubleStart[3].Button1:=TRUE;
DB8050_DriveControl.DoubleStart[3].Button2:=TRUE;
DB8050_DriveControl.DoubleStart[4].Button1:=TRUE;
DB8050_DriveControl.DoubleStart[4].Button2:=TRUE;

DB8000_Control.Machine.Emg_Stop[0]:=TRUE;
DB8000_Control.Machine.Emg_Stop[1]:=TRUE;
DB8000_Control.Machine.Emg_Stop[2]:=TRUE;
DB8000_Control.Machine.Emg_Stop[3]:=TRUE;
DB8000_Control.Machine.Emg_Stop[4]:=TRUE;

DB8000_Control.Machine.SafetyDoor[0]:=TRUE;
DB8000_Control.Machine.SafetyDoor[1]:=TRUE;
DB8000_Control.Machine.SafetyDoor[2]:=TRUE;
DB8000_Control.Machine.SafetyDoor[3]:=TRUE;
DB8000_Control.Machine.SafetyDoor[4]:=TRUE;
DB8000_Control.Machine.SafetyDoor[5]:=TRUE;
DB8000_Control.Machine.SafetyDoor[6]:=TRUE;
DB8000_Control.Machine.SafetyDoor[7]:=TRUE;



