FB_Sensor_instance[1](
	ioSensor:= DB7050_DriveControl.Sensor[1],
	iSensor:=IX7101_0_物料有无检测Sensor1,
	iName:="物料有无检测Sensor1");
///////
///////
///////

FB_Sensor_instance[2](
	ioSensor:= DB7050_DriveControl.Sensor[2],
	iSensor:=IX7101_1_物料有无检测Sensor2,
	iName:="物料有无检测Sensor2");
///////
///////
///////

FB_Sensor_instance[3](
	ioSensor:= DB7050_DriveControl.Sensor[3],
	iSensor:=IX7107_0_平台1物料有无检测Sensor3,
	iName:="平台1物料有无检测Sensor3");
///////
///////
///////

FB_Sensor_instance[4](
	ioSensor:= DB7050_DriveControl.Sensor[4],
	iSensor:=IX7107_1_平台2物料有无检测Sensor4,
	iName:="平台2物料有无检测Sensor4");
///////
///////
///////
