
// 
//  :=DB1000_Control.Machine.StartLamp;
//  :=DB1000_Control.Machine.StopLamp;
//  :=DB1000_Control.Machine.ResetLamp;
//  :=DB1000_Control.Machine.StartLamp;
//  :=DB1000_Control.Machine.StopLamp;
//  :=DB1000_Control.Machine.ResetLamp;
//  :=DB1000_Control.Machine.StartLamp;
//  :=DB1000_Control.Machine.StopLamp;
//  :=DB1000_Control.Machine.ResetLamp;

// :=DB1000_Control.Machine.RedLightHouse;
// :=DB1000_Control.Machine.YeLightHouse;	
// :=DB1000_Control.Machine.GrLightHouse;
// :=DB1000_Control.Machine.Buzzer;
// :=DB1000_Control.Machine.Light;
   
 