
// 
// QX7001_0_OP07启动按钮指示灯HMI:=DB7000_Control.Machine.StartLamp;
// QX7001_1_OP07停止按钮指示灯HMI:=DB7000_Control.Machine.StopLamp;
// QX7001_2_OP07复位按钮指示灯HMI:=DB7000_Control.Machine.ResetLamp;
// QX7002_1_OP07三色灯红:=DB7000_Control.Machine.RedLightHouse;
// QX7002_2_OP07三色灯黄:=DB7000_Control.Machine.YeLightHouse;	
// QX7002_3_OP07三色灯绿:=DB7000_Control.Machine.GrLightHouse;
// //QX7002_3_OP07三色灯绿:=DB7000_Control.Machine.Buzzer;
// QX7002_4_OP07蜂鸣器:=DB7000_Control.Machine.Buzzer;
// QX7002_5_OP07照明灯:=DB7000_Control.Machine.Light;
//         
// 
// 
// 




        