

//状态映射
Monitor[0].Status:=Status.0;
Monitor[1].Status:=Status.1;
Monitor[2].Status:=Status.2;
Monitor[3].Status:=Status.3;
Monitor[4].Status:=Status.4;
Monitor[5].Status:=Status.5;
Monitor[6].Status:=Status.6;
Monitor[7].Status:=Status.7;
Monitor[8].Status:=Status.8;
Monitor[9].Status:=Status.9;
Monitor[10].Status:=Status.10;
Monitor[11].Status:=Status.11;
Monitor[12].Status:=Status.12;
Monitor[13].Status:=Status.13;
Monitor[14].Status:=Status.14;
Monitor[15].Status:=Status.15;

