
// 
// QX8001_0_OP08启动按钮指示灯HMI:=DB3000_Control.Machine.StartLamp;
// QX8001_1_OP08停止按钮指示灯HMI:=DB3000_Control.Machine.StopLamp;
// QX8001_2_OP08复位按钮指示灯HMI:=DB3000_Control.Machine.ResetLamp;
// QX8001_3_OP08启动按钮指示灯左:=DB3000_Control.Machine.StartLamp;
// QX8001_4_OP08停止按钮指示灯左:=DB3000_Control.Machine.StopLamp;
// QX8001_5_OP08复位按钮指示灯左:=DB3000_Control.Machine.ResetLamp;
// QX8001_6_OP08启动按钮指示灯右:=DB3000_Control.Machine.StartLamp;
// QX8001_7_OP08停止按钮指示灯右:=DB3000_Control.Machine.StopLamp;
// QX8002_0_OP08复位按钮指示灯右:=DB3000_Control.Machine.ResetLamp;
// 
// QX8002_1_OP08三色灯红:=DB3000_Control.Machine.RedLightHouse;
// QX8002_2_OP08三色灯黄:=DB3000_Control.Machine.YeLightHouse;	
// QX8002_3_OP08三色灯绿:=DB3000_Control.Machine.GrLightHouse;
// QX8002_4_OP08蜂鸣器:=DB3000_Control.Machine.Buzzer;
// QX8002_5_OP08照明灯:=DB3000_Control.Machine.Light;
//    
 