


// //轴实例化
// FB_Axis_Instance[1](
// 	ioAxis:=  , 
// 	ioAxisCtrl:= DB7050_DriveControl.AxisCtrl[1], 
// 	iName:="上料X1轴",
// 	iEstop:= DB7000_Control.Machine.EmgSafetyRelay, 
// 	iSafeDoor:= DB7000_Control.Machine.SafetyDoorRelay, 
// 	iLightCurtain:=NOT DB7070_Fault.Run.LightCurtain, 
// 	iMode:= DB7000_Control.Mode, 
// 	iSpeed:= DB7000_Control.Machine.Speed, 
// 	iIntermediateStop:= TRUE, 
// 	iIC_Home:= TRUE,
// 	iIC_ABS:= TRUE,
// 	iIC_JOG:= TRUE
// 	);
// 
// 	
// 	
// 	
	
	
	
	