

DB7000_Control.Machine.OP_StartButton:=	FALSE;
DB7000_Control.Machine.OP_StopButton:=	FALSE;
DB7000_Control.Machine.OP_ResetButton:=	FALSE;
DB7000_Control.Machine.OP_AutoManual:=	FALSE;
DB7000_Control.Machine.AirPresure:=		TRUE;

 DB7000_Control.Machine.Emg_Stop[0]:=TRUE;
DB7000_Control.Machine.Emg_Stop[1]:=TRUE;

DB7000_Control.Machine.LightCurtain[0]:=TRUE; 


DB7000_Control.Machine.Emg_Stop[0]:=TRUE;
DB7000_Control.Machine.SafetyDoor[1]:=TRUE;
DB7000_Control.Machine.SafetyDoor[2]:=TRUE;
DB7000_Control.Machine.SafetyDoor[3]:=TRUE;
DB7000_Control.Machine.SafetyDoor[4]:=TRUE;
DB7000_Control.Machine.SafetyDoor[5]:=TRUE;
DB7000_Control.Machine.SafetyDoor[6]:=TRUE;
DB7000_Control.Machine.SafetyDoor[7]:=TRUE;
DB7000_Control.Machine.SafetyDoor[8]:=TRUE;
 


